### ISSUE TITLE
Add Architecture Diagram

### ISSUE THREAD

**Issue by wim-de-groot** [Hogeschool-Leiden/GameEngine#8]
Add class diagram created in Lucidchart, using the Lucidchart GitHub app.

**Comment by degrootwim** [comment]
https://www.lucidchart.com/invitations/accept/d5de9ee3-3b6e-4bfb-8d21-1b039c0f64f4

**Comment by degrootwim** [comment]
<div style="width: 640px; height: 480px; margin: 10px; position: relative;"><iframe allowfullscreen frameborder="0" style="width:640px; height:480px" src="https://www.lucidchart.com/documents/embeddedchart/105626cd-a736-41de-aa65-de48eef8cd02" id="TDlHdas2uN.q"></iframe></div>

**Comment by degrootwim** [comment]
https://www.lucidchart.com/invitations/accept/d5de9ee3-3b6e-4bfb-8d21-1b039c0f64f4

**Comment by degrootwim** [comment]
[https://www.lucidchart.com/invitations/accept/d5de9ee3-3b6e-4bfb-8d21-1b039c0f64f4](url)

**Comment by degrootwim** [comment]
[https://www.lucidchart.com/documents/view/105626cd-a736-41de-aa65-de48eef8cd02
](url)

**Comment by wim-de-groot** [comment]
https://www.lucidchart.com/documents/view/105626cd-a736-41de-aa65-de48eef8cd02
